/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package compile.view;

import compiler.exceptions.IsLexicalExceptions;
import compiler.lexico.IsScanner;
import compiler.lexico.Token;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        setLocationRelativeTo(null);
        saida.setEditable(false);
//        txtEntrada.append(txtEntrada.getText() + "\t");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        saida = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        executarBtn = new javax.swing.JButton();
        limparBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        tempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Analizador Lexico");

        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);
        jScrollPane1.setViewportView(txtEntrada);

        saida.setColumns(20);
        saida.setRows(5);
        jScrollPane2.setViewportView(saida);

        jLabel2.setText("Entrada");

        jLabel3.setText("Saida");

        executarBtn.setBackground(new java.awt.Color(0, 153, 255));
        executarBtn.setForeground(new java.awt.Color(255, 255, 255));
        executarBtn.setText("Executar");
        executarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executarBtnActionPerformed(evt);
            }
        });

        limparBtn.setBackground(new java.awt.Color(255, 0, 0));
        limparBtn.setForeground(new java.awt.Color(255, 255, 255));
        limparBtn.setText("Limpar");
        limparBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparBtnActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo Token", "Token", "Linha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(2).setMaxWidth(50);
        }

        jLabel4.setText("Erros");

        tempo.setForeground(new java.awt.Color(0, 204, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(limparBtn)
                                .addGap(18, 18, 18)
                                .addComponent(executarBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(225, 225, 225))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tempo)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(tempo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(executarBtn)
                            .addComponent(limparBtn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void executarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executarBtnActionPerformed
            saida.setText("");
            long start = System.currentTimeMillis();
            long atual = 0;
            int i = 0;
        if(txtEntrada.getText().isEmpty()){
                 JOptionPane.showMessageDialog(this, "Por favor digite algo");
                 
                 
                 return;
             }
              ArrayList<String> tokens =  new ArrayList<String>();
              ArrayList<Token> toks =  new ArrayList<Token>();
             String saidaText = "";
              Token token = null;
              Token tk_error = null;
               IsScanner sc = new IsScanner(txtEntrada.getText() + " \t");

      
//        IsScanner sc = new IsScanner("abc123 \n > \n 123 \n aaa^ \n aaa \n 12abc ");
              
        do{
              try{
             token = sc.proximoToken();
           if(token != null){
             //  saidaText += token;
             //tokens.add(token+"");
             toks.add(token);
              i += 1;
           }
           
          //----------------
          
             }catch(IsLexicalExceptions e){
            
           // saidaText = e.getMessage();
           tokens.add(e.getMessage());
            saida.setForeground(Color.red);
            continue;
         
    }catch(Exception e){
            System.out.println("general error");
    }   
          //---------------
           
           
              System.out.println("i " + i);
        }while (token != null);
  atual = System.currentTimeMillis();
            System.out.println("atual " + atual);
           
 
        System.out.println("TKs " + tokens.toString());
        //if(saidaText == ""){
            
            if(tokens.size() == 0){
                saida.setText("Nenhum erro lexico encontrado");
            }else{
                 // saida.setForeground(Color.red);
                  tokens.forEach( (n) -> saida.append(n + " \n"));
            }
            
          

            
            
           // saidaText = "Nenhum erro lexico encontrado.";
            saida.append(saidaText);
            saida.setForeground(Color.black);
           
            
               DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
               tabela.setShowVerticalLines(true);
                tabela.setGridColor(Color.BLACK);
                
               modelo.setRowCount(0);
            for(Token x : toks){
                modelo.addRow(new Object[]{
              Token.TK_TEXT[x.getType()],
              x.getText(),
              x.getLine()
            });
            }
            
       // }else{
        //      System.out.println("Todos elementos : " + tokens.toString());
     // saida.append(saidaText);
     
      
      
        //}
       
//      txtEntrada.append("\toj");
       System.out.println("txt texto " + txtEntrada.getText() + " fim"); 
       long end = System.currentTimeMillis();
        System.out.println(start);
        System.out.println(end);
       // System.out.println("tokens " + tokens.get(0).getType());
        System.out.println("tempo " + (end - start));
        long execTime = end - start;
        tempo.setText("executado em "+ execTime + " millisegundos");
    }//GEN-LAST:event_executarBtnActionPerformed

    private void limparBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparBtnActionPerformed
        // TODO add your handling code here:
        
        txtEntrada.setText("");
        saida.setText("");
            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            modelo.setRowCount(0);
            tempo.setText("");
    }//GEN-LAST:event_limparBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton executarBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton limparBtn;
    private javax.swing.JTextArea saida;
    private javax.swing.JTable tabela;
    private javax.swing.JLabel tempo;
    private javax.swing.JTextArea txtEntrada;
    // End of variables declaration//GEN-END:variables
}
